In [1]:
import numpy as np
# Creating array using lists.
arr=np.array([1,2,3,4,5]) #1D
arr2=np.array([[1,2,3],[4,5,6]])#2D
#Creating from scratch
arra3=np.zeros((3,3))
arr3=np.zeros((2,3))
arr4=np.ones((2,4))
arr5=np.full((3,5),45)
arr6=np.eye(4)
arr7=np.arange(1,10,2)
arr8=np.linspace(0,1,5)

In [2]:
arr8

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [3]:
import numpy as np
# Creating array using lists.
arr=np.array([1,2,3,4,5]) #1D
arr2=np.array([[1,2,3],[4,5,6]])#2D
#Creating from scratch
arra3=np.zeros((3,3))
arr3=np.zeros((2,3))
arr4=np.ones((2,4))
arr5=np.full((3,5),45)
arr6=np.eye(4) #indentity matrix of order 4
arr7=np.arange(1,10,2)
arr8=np.linspace(0,1,5)
#array property
print(arr7.shape)
print(arr8.size)
print(arr6.ndim)
print(arr4.dtype)
#explicitly changeing dtype
new=np.array(arr4,dtype=np.int32)
print(new.dtype)

(5,)
5
2
float64
int32


In [4]:
#Reshaping and flattening
new2=arr4.reshape(4,2)
print(new2.shape)
print(new2)
new3=arr4.flatten()
print(new3)

(4, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1.]
