## SLICING AND INDEXING.

In [1]:
import numpy as np
arr=np.array([10,20,30,40])
#Indexing is same as python
print(arr[2])

30


In [2]:
#Slicing 
print(arr[1:3])

[20 30]


In [3]:
#Slicing returns a view, not a copy! Changes affect the original array.
slice=arr[1:3]
slice[0]=100
print(arr)

[ 10 100  30  40]


In [4]:
#for actual copy use copy method.
arr1=np.array([12,13,14,15])
copy=arr1[1:].copy()
print(copy)
copy[2]=23
print(copy)
print(arr1)

[13 14 15]
[13 14 23]
[12 13 14 15]


In [5]:
#Fancy indexing 
array=np.array([1,2,3,4,5,6,7,8,9,10])
idx=[2,5,6]
print(idx)
print(array[[1,2]])

#Boolean masking
mask=array>5
print(array[mask])
print(array[array%2==0])

[2, 5, 6]
[2 3]
[ 6  7  8  9 10]
[ 2  4  6  8 10]
