### Multidimensional indexing and axes ..

In [8]:
import numpy as np
#2D array
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(np.sum(arr,axis=0))#sum along rows
print(np.sum(arr,axis=1))#sum along column

[12 15 18]
[ 6 15 24]


In [13]:
print(arr[1,2])
print(arr[0:2,2])

6
[3 6]


In [15]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  

(2, 2, 3)


In [17]:
print(arr3D[0,1,2])

6


In [18]:
print(arr3D[:,0,:])

[[1 2 3]
 [7 8 9]]


In [19]:
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
