In [4]:
import numpy as np
arr=np.arange(1,10)

In [5]:
np.mean(arr)

np.float64(5.0)

In [7]:
np.std(arr)

np.float64(2.581988897471611)

In [8]:
np.var(arr)

np.float64(6.666666666666667)

In [9]:
np.min(arr)

np.int64(1)

In [10]:
np.max(arr)

np.int64(9)

In [11]:
np.sum(arr)

np.int64(45)

In [12]:
np.prod(arr)

np.int64(362880)

In [13]:
np.median(arr)

np.float64(5.0)

In [15]:
np.percentile(arr,20)

np.float64(2.6)

In [16]:
np.argmin(arr)

np.int64(0)

In [17]:
np.argmax(arr)

np.int64(8)

In [18]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.diff(arr)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [21]:
np.log(arr)


array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [22]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])