### Q:1 Create a 3×3 array filled with random numbers and print its shape.

In [1]:
import numpy as np
arr=np.random.rand(3,3)
print(arr)
print("Shape Of Array Is = ",arr.shape)


[[0.55912502 0.65942137 0.90747756]
 [0.17603303 0.78739757 0.55245375]
 [0.70110466 0.34761504 0.89092253]]
Shape Of Array Is =  (3, 3)


### Q:2 Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [2]:
floatarray=np.array([1.1,2.2,3.3],dtype=int)#Dtype used to convert array when it created
print(floatarray)
arr=np.array([1.1,2.2,3.3])
int_array=arr.astype(int)
print(int_array)

[1 2 3]
[1 2 3]


### Q:3 Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [3]:
arr=np.array([1,2,3,4,5,6])
print(arr[[1,3,5]])

[2 4 6]


### Q:4 Reshape a 1D array of size 9 into a 3×3 matrix.

In [4]:
arr=np.arange(1,10)#1D array of 9 elements
matrix=arr.reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Q:5 Use boolean masking to filter numbers greater than 50 in an array.

In [5]:
arr=np.arange(40,60,2)
print(arr[arr>50])

[52 54 56 58]
